### ISSUE TITLE
Can't use phpstan-yii2 if there are helper functions in config

### ISSUE THREAD

**Issue by ddinchev** [proget-hq/phpstan-yii2#12]
This is my `phpstan.neon`.

```
includes:
	- vendor/proget-hq/phpstan-yii2/extension.neon
parameters:
    autoload_files:
        - %rootDir%/../../../common/helpers.php
    yii2:
        config_path: %rootDir%/../../../config/web.php
```

I use functions defined in `%rootDir%/../../../common/helpers.php` in my config file, however `phpstan-yii2`'s services seem to be executed before that file is included and it fails with a message that no such message exists.
