### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by pappfer** [proget-hq/phpstan-yii2#33]
I installed PhpStan and this extension using Composer in my Yii2 project, created the `phpstan.neon` config file with the following content:

```
includes:
	- vendor/proget-hq/phpstan-yii2/extension.neon
parameters:
    yii2:
        config_path: %rootDir%/../../../config/test.php
```

After running it the first time, I run into issue #27, but fixed it by `require_once` tip mentioned on the same issue.
After running it again, the only output I get is this: `Note: Using configuration file /var/www/proteus/phpstan.neon.`

It doesn't give me anything else. It is a huge project, I'm sure there are tons of issues it should list, but I only get an empty output. What am I doing wrong?
